language: c

compiler:
  - gcc
  - clang

before_install:
  - sudo add-apt-repository --yes ppa:kalakris/cmake
  - sudo apt-get update -qq
  - sudo apt-get install cmake

script:
  - mkdir build && cd build
  - cmake .. -DENABLE_COVERAGE=On
  - make
  - make test

after_success:
  - VERBOSE=1 make gcov
  - bash <(curl -s https://codecov.io/bash)
